= A Tour of the Refactoring
:compat-mode:

== Step One: Independent Deployability

There's no real hope of having any sort of success with microservices as long as we're in the state where the same exact codebase must be deployed to run the website and to support managing individual stores. The eventual microservices we build will likely look very different in each context. So our first step is to create two independently deployable monoliths, each supporting a `common` shared library. The scope of the shared library gives us a real picture of just how tightly coupled the site and store code really are.

So in this stage we:

* Create a Gradle subproject structure: `common`, `store`, `site`.
* Refactor `build.gradle` to manage three subprojects, and we add `settings.gradle`.
* Parcel code out into the various subprojects.
* Fix compile errors and failing tests.

== Step Two: Finish an Existing Feature

We actually stopped work in progress when we completed Step One. A team has been laboring to finish up the order management screen for the stores, but has been unable to deliver due to churn on the website. Now that the applications are independently deployable, the store team can complete that UI feature and deploy it without waiting on the site team.

So in this stage we:

* Add a `StoreService` method, `orderDetails`.
* Add a `StoreController` method, `orderDetails`.
* Add a UI template, `orderDetails.html`.
